excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://leticiassenna.github.io
name: POO2 - 2015-2
description: This blog contains all the content on updates made on GitHub related to work on the POO2 discipline in semetre 2015-2
author: Leticia Senna
avatar: http://www.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?s=120&d=mm&r=g
ga_domain: 
ga_tracking_id: 